/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Contact: typeof import('./src/components/Sections/Contact.vue')['default']
    Education: typeof import('./src/components/Sections/Education.vue')['default']
    History: typeof import('./src/components/Sections/History.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    Personal: typeof import('./src/components/Sections/Personal.vue')['default']
    Projects: typeof import('./src/components/Sections/Projects.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/Section.vue')['default']
    Welcome: typeof import('./src/components/Welcome.vue')['default']
  }
}
